### ISSUE TITLE
Adding Flock to awesome-elixir

### ISSUE THREAD

**Issue by h4cc** [chrismccord/flock#1]
Hi there, 
when someday this repository contains working code, might you please reopen this ticket?

https://github.com/h4cc/awesome-elixir/issues/283

Thanks.

**Comment by CrowdHailer** [comment]
@chrismccord as there is still no code in this repo, did something better come along that made this project unnecessary?

**Comment by chrismccord** [comment]
@CrowdHailer we went with a different name :) https://github.com/phoenixframework/firenest
